"""The labels, the control numbers and the header text the SMC-PAD input profile declares."""

PROFILE_DOCTYPE = "<!DOCTYPE InputProfile>"
MANUFACTURER = "M-VAVE"
MODEL = "SMC-PAD"
# QLC+ names a profile "<Manufacturer> <Model>" (QLCInputProfile::name), and
# that is the string a workspace's <Input Profile="..."> has to carry.
PROFILE_NAME = f"{MANUFACTURER} {MODEL}"

KNOBS = 8
FIRST_KNOB_CC = 30
EDGE_BUTTONS = (
    (25, "< (pagina anterior)"),
    (26, "> (pagina siguiente)"),
    (27, "Play (libre)"),
    # The manual names CC 28 STOP; the show's console calls its button Pausa.
    (28, "Stop (PARAR TODO)"),
    (29, "Rec (APAGON)"),
)

HEADER_COMMENT = """
  Generated by `qlctool input-profile` from
  qlctool/generate/smc_pad_device.py in spectalive/qlctool - edit that map,
  not this file, or the profile and the show's bindings drift apart again.

  Measured 2026-08-29 over USB and Bluetooth (midicap.swift in
  spectalive/smc-pad). Only what was measured is declared. The
  device splits its controls across two MIDI channels, so the QLC+ MIDI input
  must be set to MIDI channel "1-16" (omni); in omni QLC+ ORs the 0-based MIDI
  channel into bits 12+ of the channel number and offsets notes by 128:

    pads    ch10 -> 36992 + note   (bank 1 notes 36-51, bank 2 52-67)
    knobs   ch1  -> the CC number  (CC 30-37, absolute 0-127)
    buttons ch1  -> the CC number  (CC 25-29, 127 press / 0 release)

  Pads are numbered as the panel silkscreens them: PAD1 bottom-left, PAD13
  top-left. PAD BANK moves every pad one bank (+16 notes) and is where the
  console's JUGAR/page-2 hooks live; SHIFT sends no MIDI at all.
"""
