"""Write the QLC+ input profile for the SMC-PAD from the map the show uses.

The profile is what QLC+ shows a person in the input tab: it turns the raw
channel number a binding carries into "Pad 13" or "Knob 1". It is only a label
layer - a binding fires with or without it - which is exactly why the shipped
one rotted unnoticed for a day: it still declared the pad's factory notes 4-19
while every binding in the workspace had moved to 36-51, so the tab named the
wrong control for every pad on the surface.

Generating it from `smc_pad_device` removes that failure: the profile and the
bindings now cannot disagree, and `tests/test_input_profile.py` fails if the
shipped file drifts from what this builds.
"""

from lxml import etree

from ..constants import XML_DECLARATION
from .smc_pad_device import (
    OMNI_CHANNEL_SHIFT,
    PAD_MIDI_CHANNEL,
    PADS,
    control_channel,
    pad_channel,
)

PROFILE_NS = "http://www.qlcplus.org/InputProfile"
PROFILE_DOCTYPE = "<!DOCTYPE InputProfile>"
MANUFACTURER = "M-VAVE"
MODEL = "SMC-PAD"
# QLC+ names a profile "<Manufacturer> <Model>" (QLCInputProfile::name), and
# that is the string a workspace's <Input Profile="..."> has to carry.
PROFILE_NAME = f"{MANUFACTURER} {MODEL}"

# Channel aftertouch is one QLC+ channel per MIDI channel, at offset 512
# (CHANNEL_OFFSET_CHANNEL_AFTERTOUCH). The pads send it while held.
AFTERTOUCH_OFFSET = 512

PADS_PER_ROW = 4
KNOBS = 8
FIRST_KNOB_CC = 30
EDGE_BUTTONS = (
    (25, "< (pagina anterior)"),
    (26, "> (pagina siguiente)"),
    (27, "Play (libre)"),
    (28, "Pausa (PARAR TODO)"),
    (29, "Rec (APAGON)"),
)

HEADER_COMMENT = """
  Generated by `qlctool input-profile` from
  tools/qlctool/qlctool/generate/smc_pad_device.py - edit that map, not this
  file, or the profile and the show's bindings drift apart again.

  Measured 2026-08-29 over USB and Bluetooth (tools/smc-pad/midicap.swift). The
  device splits its controls across two MIDI channels, so the QLC+ MIDI input
  must be set to MIDI channel "1-16" (omni); in omni QLC+ ORs the 0-based MIDI
  channel into bits 12+ of the channel number and offsets notes by 128:

    pads    ch10 -> 36992 + note   (bank 1 notes 36-51, bank 2 52-67)
    knobs   ch1  -> the CC number  (CC 30-37, absolute 0-127)
    buttons ch1  -> the CC number  (CC 25-29, 127 press / 0 release)

  Pads are numbered as the panel silkscreens them: PAD1 bottom-left, PAD13
  top-left. PAD BANK moves every pad one bank (+16 notes) and is where the
  console's manual page lives; SHIFT sends no MIDI at all.
"""


def build_input_profile() -> bytes:
    """The .qxi file, ready to write, for the pad this show is driven from."""
    root = etree.Element(f"{{{PROFILE_NS}}}InputProfile", nsmap={None: PROFILE_NS})
    creator = etree.SubElement(root, f"{{{PROFILE_NS}}}Creator")
    etree.SubElement(creator, f"{{{PROFILE_NS}}}Name").text = "qlctool"
    etree.SubElement(creator, f"{{{PROFILE_NS}}}Version").text = "5.2.2"
    etree.SubElement(creator, f"{{{PROFILE_NS}}}Author").text = "Cristian Deluxe"
    etree.SubElement(root, f"{{{PROFILE_NS}}}Manufacturer").text = MANUFACTURER
    etree.SubElement(root, f"{{{PROFILE_NS}}}Model").text = MODEL
    etree.SubElement(root, f"{{{PROFILE_NS}}}Type").text = "MIDI"
    root.append(etree.Comment(HEADER_COMMENT))

    for bank in (1, 2):
        for pad in _pads_top_down():
            label = f"Pad {pad}" if bank == 1 else f"Banco 2 - Pad {pad}"
            _channel(root, pad_channel(pad, bank=bank), label, "Button")
    for knob in range(1, KNOBS + 1):
        _channel(root, control_channel(FIRST_KNOB_CC + knob - 1), f"Knob {knob}", "Knob")
    for cc, label in EDGE_BUTTONS:
        _channel(root, control_channel(cc), label, "Button")
    _channel(
        root,
        ((PAD_MIDI_CHANNEL - 1) << OMNI_CHANNEL_SHIFT) + AFTERTOUCH_OFFSET,
        "Presion de pad (channel aftertouch)",
        "Slider",
    )

    body = etree.tostring(root, pretty_print=True, encoding="unicode")
    return f"{XML_DECLARATION}\n{PROFILE_DOCTYPE}\n{body}".encode()


def _pads_top_down() -> list[int]:
    """Pad numbers row by row from the top, the order a person sees them."""
    rows = PADS // PADS_PER_ROW
    return [
        pad
        for row in range(rows - 1, -1, -1)
        for pad in range(row * PADS_PER_ROW + 1, (row + 1) * PADS_PER_ROW + 1)
    ]


def _channel(root: etree._Element, number: int, name: str, type_: str) -> None:
    channel = etree.SubElement(root, f"{{{PROFILE_NS}}}Channel", Number=str(number))
    etree.SubElement(channel, f"{{{PROFILE_NS}}}Name").text = name
    etree.SubElement(channel, f"{{{PROFILE_NS}}}Type").text = type_
