"""A whole GDTF fixture type from one QLC+ definition.

Every mode the definition declares becomes a DMX mode over the same geometry,
so the one file serves whichever mode the patch picks. The fixture type ID is
derived from manufacturer and model, so regenerating the export does not hand
BlenderDMX a "new" fixture type each time and make it re-import the models.

The attribute definitions are not written by hand: pygdtf regenerates them
from the attributes the channels actually use, against the Annex B data it
ships, and a name it does not know is an error here rather than a file
BlenderDMX quietly mis-reads.
"""

import uuid
from datetime import UTC, datetime
from pathlib import Path

import pygdtf
from pygdtf.utils import regenerate_attribute_definitions

from ..definition import FixtureDefinition
from .build_channels import build_channels
from .build_geometry import build_geometry
from .build_wheels import build_wheels
from .built_fixture_type import BuiltFixtureType
from .gdtf_name import gdtf_name

NAMESPACE = uuid.UUID("6c1f0b2e-4f3a-4d55-9a7e-7c2b7f2a0d31")


def build_fixture_type(definition: FixtureDefinition, gobo_dir: Path | None) -> BuiltFixtureType:
    fixture = pygdtf.FixtureType()
    fixture.data_version = "1.2"
    fixture.name = gdtf_name(definition.model)
    fixture.short_name = gdtf_name(definition.model)[:16]
    fixture.long_name = gdtf_name(f"{definition.manufacturer} {definition.model}")
    fixture.manufacturer = gdtf_name(definition.manufacturer)
    fixture.description = (
        f"Converted from the QLC+ definition by qlctool ({definition.fixture_type})"
    )
    fixture.fixture_type_id = str(
        uuid.uuid5(NAMESPACE, f"{definition.manufacturer}/{definition.model}")
    )

    plan = build_geometry(definition)
    wheels = build_wheels(definition, gobo_dir)
    fixture.models = plan.models
    fixture.geometries = pygdtf.Geometries([plan.root])
    fixture.wheels = wheels.wheels
    fixture.dmx_modes = [
        pygdtf.DmxMode(
            name=gdtf_name(mode),
            geometry=plan.root_name,
            _dmx_channels=build_channels(definition, mode, plan, wheels),
            fixture_type=fixture,
        )
        for mode in definition.modes
    ]

    attributes = regenerate_attribute_definitions(fixture)
    if attributes["missing_attributes"]:
        raise ValueError(
            f"{definition.manufacturer} {definition.model}: attributes GDTF does not "
            f"define: {', '.join(sorted(attributes['missing_attributes']))}"
        )
    fixture.activation_groups = attributes["activation_groups"]
    fixture.feature_groups = attributes["feature_groups"]
    fixture.attributes = attributes["attributes"]
    fixture.revisions = pygdtf.Revisions(
        [
            pygdtf.Revision(
                text="Generated by qlctool from the QLC+ definition",
                date=datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%S"),
                user_id=0,
                modified_by=f"pygdtf {pygdtf.__version__}",
            )
        ]
    )
    return BuiltFixtureType(fixture_type=fixture, media=wheels.media)
